/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Metodos.MetodosAmostragem;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author CPD
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }
    
    MetodosAmostragem amostragem = new MetodosAmostragem();
   
    //Getters
    public JTextField getFieldTamanhoAmostraComRep() {
        return fieldTamanhoAmostraComRep;
    }

    public JTextField getFieldTamanhoAmostraSemRep() {
        return fieldTamanhoAmostraSemRep;
    }

    public JTextField getFieldTamanhoAmostraSistematica() {
        return fieldTamanhoAmostraSistematica;
    }

    public JTextField getFieldTamanhoPopulacaoComRep() {
        return fieldTamanhoPopulacaoComRep;
    }

    public JTextField getFieldTamanhoPopulacaoSemRep() {
        return fieldTamanhoPopulacaoSemRep;
    }

    public JTextField getFieldTamanhoPopulacaoSistematica() {
        return fieldTamanhoPopulacaoSistematica;
    }

    public JTextArea getTextAreaResultadoComReposicao() {
        return textAreaResultadoComReposicao;
    }

    public JTextArea getTextAreaResultadoSemReposicao() {
        return textAreaResultadoSemReposicao;
    }

    public JTextArea getTextAreaResultadoSistematica() {    
        return textAreaResultadoSistematica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogAleatoriaComReposicao = new javax.swing.JDialog();
        panelComRep = new javax.swing.JPanel();
        panelEntradaComRep = new javax.swing.JPanel();
        fieldTamanhoPopulacaoComRep = new javax.swing.JTextField();
        fieldTamanhoAmostraComRep = new javax.swing.JTextField();
        btnCancelarComRep = new javax.swing.JButton();
        btnExecutarComRep = new javax.swing.JButton();
        panelResultadoComRep = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaResultadoComReposicao = new javax.swing.JTextArea();
        dialogAleatoriaSemReposicao = new javax.swing.JDialog();
        panelAleatoriaSemReposicao = new javax.swing.JPanel();
        panelEntradaSemRep = new javax.swing.JPanel();
        fieldTamanhoPopulacaoSemRep = new javax.swing.JTextField();
        fieldTamanhoAmostraSemRep = new javax.swing.JTextField();
        btnCancelarSemRep = new javax.swing.JButton();
        btnExecutarSemRep = new javax.swing.JButton();
        panelResultadoSemRep = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textAreaResultadoSemReposicao = new javax.swing.JTextArea();
        dialogAmostragemSistematica = new javax.swing.JDialog();
        panelSistematica = new javax.swing.JPanel();
        panelEntradaSistematica = new javax.swing.JPanel();
        fieldTamanhoPopulacaoSistematica = new javax.swing.JTextField();
        fieldTamanhoAmostraSistematica = new javax.swing.JTextField();
        btnCancelarSistematica = new javax.swing.JButton();
        btnExecutarSistematica = new javax.swing.JButton();
        panelResultadoSistematica = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        textAreaResultadoSistematica = new javax.swing.JTextArea();
        jPanelPrincipal = new javax.swing.JPanel();
        JTabbedPane = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAleatoria = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSobreAleatoria = new javax.swing.JTextArea();
        btnComReposicao = new javax.swing.JButton();
        btnSemReposicao = new javax.swing.JButton();
        jPanelSistematica = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaSobreSistematica = new javax.swing.JTextArea();
        btnSistematica = new javax.swing.JButton();
        jPanelSobre = new javax.swing.JPanel();

        dialogAleatoriaComReposicao.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogAleatoriaComReposicao.setTitle("Amostragem Aleatória - Com Reposição");
        dialogAleatoriaComReposicao.setBackground(new java.awt.Color(255, 255, 255));
        dialogAleatoriaComReposicao.setMinimumSize(new java.awt.Dimension(460, 350));
        dialogAleatoriaComReposicao.setName("Amostragem Aleatória - Com Reposição");
        dialogAleatoriaComReposicao.setResizable(false);

        panelComRep.setBackground(new java.awt.Color(255, 255, 255));

        panelEntradaComRep.setBackground(new java.awt.Color(255, 255, 255));
        panelEntradaComRep.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Entrada de dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        fieldTamanhoPopulacaoComRep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldTamanhoPopulacaoComRep.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldTamanhoPopulacaoComRep.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Tamanho da população"));
        fieldTamanhoPopulacaoComRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTamanhoPopulacaoComRepActionPerformed(evt);
            }
        });

        fieldTamanhoAmostraComRep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldTamanhoAmostraComRep.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldTamanhoAmostraComRep.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Tamanho da amostra"));

        javax.swing.GroupLayout panelEntradaComRepLayout = new javax.swing.GroupLayout(panelEntradaComRep);
        panelEntradaComRep.setLayout(panelEntradaComRepLayout);
        panelEntradaComRepLayout.setHorizontalGroup(
            panelEntradaComRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradaComRepLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(fieldTamanhoPopulacaoComRep, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTamanhoAmostraComRep, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEntradaComRepLayout.setVerticalGroup(
            panelEntradaComRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaComRepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEntradaComRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTamanhoPopulacaoComRep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTamanhoAmostraComRep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnCancelarComRep.setText("Cancelar");
        btnCancelarComRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarComRepActionPerformed(evt);
            }
        });

        btnExecutarComRep.setText("Executar");
        btnExecutarComRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarComRepActionPerformed(evt);
            }
        });

        panelResultadoComRep.setBackground(new java.awt.Color(255, 255, 255));
        panelResultadoComRep.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        textAreaResultadoComReposicao.setEditable(false);
        textAreaResultadoComReposicao.setColumns(20);
        textAreaResultadoComReposicao.setLineWrap(true);
        textAreaResultadoComReposicao.setRows(5);
        textAreaResultadoComReposicao.setText("\n");
        textAreaResultadoComReposicao.setWrapStyleWord(true);
        textAreaResultadoComReposicao.setBorder(null);
        jScrollPane3.setViewportView(textAreaResultadoComReposicao);

        javax.swing.GroupLayout panelResultadoComRepLayout = new javax.swing.GroupLayout(panelResultadoComRep);
        panelResultadoComRep.setLayout(panelResultadoComRepLayout);
        panelResultadoComRepLayout.setHorizontalGroup(
            panelResultadoComRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadoComRepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        panelResultadoComRepLayout.setVerticalGroup(
            panelResultadoComRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoComRepLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelComRepLayout = new javax.swing.GroupLayout(panelComRep);
        panelComRep.setLayout(panelComRepLayout);
        panelComRepLayout.setHorizontalGroup(
            panelComRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComRepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelResultadoComRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelComRepLayout.createSequentialGroup()
                        .addComponent(panelEntradaComRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelComRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelarComRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExecutarComRep, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelComRepLayout.setVerticalGroup(
            panelComRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComRepLayout.createSequentialGroup()
                .addGroup(panelComRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelComRepLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelEntradaComRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelComRepLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnExecutarComRep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarComRep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultadoComRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogAleatoriaComReposicaoLayout = new javax.swing.GroupLayout(dialogAleatoriaComReposicao.getContentPane());
        dialogAleatoriaComReposicao.getContentPane().setLayout(dialogAleatoriaComReposicaoLayout);
        dialogAleatoriaComReposicaoLayout.setHorizontalGroup(
            dialogAleatoriaComReposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelComRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogAleatoriaComReposicaoLayout.setVerticalGroup(
            dialogAleatoriaComReposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelComRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogAleatoriaComReposicao.setLocationRelativeTo(null);

        dialogAleatoriaSemReposicao.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogAleatoriaSemReposicao.setTitle("Amostragem Aleatória - Sem Reposição");
        dialogAleatoriaSemReposicao.setBackground(new java.awt.Color(255, 255, 255));
        dialogAleatoriaSemReposicao.setMinimumSize(new java.awt.Dimension(490, 420));
        dialogAleatoriaSemReposicao.setName("Amostragem Aleatória - Sem Reposição");
        dialogAleatoriaSemReposicao.setResizable(false);

        panelAleatoriaSemReposicao.setBackground(new java.awt.Color(255, 255, 255));

        panelEntradaSemRep.setBackground(new java.awt.Color(255, 255, 255));
        panelEntradaSemRep.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Entrada de dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        fieldTamanhoPopulacaoSemRep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldTamanhoPopulacaoSemRep.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldTamanhoPopulacaoSemRep.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Tamanho da população"));

        fieldTamanhoAmostraSemRep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldTamanhoAmostraSemRep.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldTamanhoAmostraSemRep.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Tamanho da amostra"));

        javax.swing.GroupLayout panelEntradaSemRepLayout = new javax.swing.GroupLayout(panelEntradaSemRep);
        panelEntradaSemRep.setLayout(panelEntradaSemRepLayout);
        panelEntradaSemRepLayout.setHorizontalGroup(
            panelEntradaSemRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradaSemRepLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(fieldTamanhoPopulacaoSemRep, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTamanhoAmostraSemRep, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEntradaSemRepLayout.setVerticalGroup(
            panelEntradaSemRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaSemRepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEntradaSemRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTamanhoPopulacaoSemRep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTamanhoAmostraSemRep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnCancelarSemRep.setText("Cancelar");
        btnCancelarSemRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSemRepActionPerformed(evt);
            }
        });

        btnExecutarSemRep.setText("Executar");
        btnExecutarSemRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarSemRepActionPerformed(evt);
            }
        });

        panelResultadoSemRep.setBackground(new java.awt.Color(255, 255, 255));
        panelResultadoSemRep.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        textAreaResultadoSemReposicao.setEditable(false);
        textAreaResultadoSemReposicao.setColumns(20);
        textAreaResultadoSemReposicao.setLineWrap(true);
        textAreaResultadoSemReposicao.setRows(5);
        textAreaResultadoSemReposicao.setText("\n");
        textAreaResultadoSemReposicao.setWrapStyleWord(true);
        textAreaResultadoSemReposicao.setBorder(null);
        jScrollPane6.setViewportView(textAreaResultadoSemReposicao);

        javax.swing.GroupLayout panelResultadoSemRepLayout = new javax.swing.GroupLayout(panelResultadoSemRep);
        panelResultadoSemRep.setLayout(panelResultadoSemRepLayout);
        panelResultadoSemRepLayout.setHorizontalGroup(
            panelResultadoSemRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadoSemRepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        panelResultadoSemRepLayout.setVerticalGroup(
            panelResultadoSemRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoSemRepLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelAleatoriaSemReposicaoLayout = new javax.swing.GroupLayout(panelAleatoriaSemReposicao);
        panelAleatoriaSemReposicao.setLayout(panelAleatoriaSemReposicaoLayout);
        panelAleatoriaSemReposicaoLayout.setHorizontalGroup(
            panelAleatoriaSemReposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAleatoriaSemReposicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAleatoriaSemReposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelResultadoSemRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAleatoriaSemReposicaoLayout.createSequentialGroup()
                        .addComponent(panelEntradaSemRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAleatoriaSemReposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelarSemRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExecutarSemRep, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelAleatoriaSemReposicaoLayout.setVerticalGroup(
            panelAleatoriaSemReposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAleatoriaSemReposicaoLayout.createSequentialGroup()
                .addGroup(panelAleatoriaSemReposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAleatoriaSemReposicaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelEntradaSemRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAleatoriaSemReposicaoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnExecutarSemRep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarSemRep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultadoSemRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogAleatoriaSemReposicaoLayout = new javax.swing.GroupLayout(dialogAleatoriaSemReposicao.getContentPane());
        dialogAleatoriaSemReposicao.getContentPane().setLayout(dialogAleatoriaSemReposicaoLayout);
        dialogAleatoriaSemReposicaoLayout.setHorizontalGroup(
            dialogAleatoriaSemReposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAleatoriaSemReposicaoLayout.createSequentialGroup()
                .addComponent(panelAleatoriaSemReposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogAleatoriaSemReposicaoLayout.setVerticalGroup(
            dialogAleatoriaSemReposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAleatoriaSemReposicaoLayout.createSequentialGroup()
                .addComponent(panelAleatoriaSemReposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        dialogAleatoriaSemReposicao.setLocationRelativeTo(null);

        dialogAmostragemSistematica.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogAmostragemSistematica.setTitle("Amostragem Sistemática");
        dialogAmostragemSistematica.setBackground(new java.awt.Color(255, 255, 255));
        dialogAmostragemSistematica.setMinimumSize(new java.awt.Dimension(460, 350));
        dialogAmostragemSistematica.setName("Amostragem Sistemática");
        dialogAmostragemSistematica.setResizable(false);

        panelSistematica.setBackground(new java.awt.Color(255, 255, 255));

        panelEntradaSistematica.setBackground(new java.awt.Color(255, 255, 255));
        panelEntradaSistematica.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Entrada de dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        fieldTamanhoPopulacaoSistematica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldTamanhoPopulacaoSistematica.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldTamanhoPopulacaoSistematica.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Tamanho da população"));

        fieldTamanhoAmostraSistematica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldTamanhoAmostraSistematica.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldTamanhoAmostraSistematica.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Tamanho da amostra"));

        javax.swing.GroupLayout panelEntradaSistematicaLayout = new javax.swing.GroupLayout(panelEntradaSistematica);
        panelEntradaSistematica.setLayout(panelEntradaSistematicaLayout);
        panelEntradaSistematicaLayout.setHorizontalGroup(
            panelEntradaSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradaSistematicaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(fieldTamanhoPopulacaoSistematica, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTamanhoAmostraSistematica, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEntradaSistematicaLayout.setVerticalGroup(
            panelEntradaSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaSistematicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEntradaSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTamanhoPopulacaoSistematica, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTamanhoAmostraSistematica, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnCancelarSistematica.setText("Cancelar");
        btnCancelarSistematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSistematicaActionPerformed(evt);
            }
        });

        btnExecutarSistematica.setText("Executar");
        btnExecutarSistematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarSistematicaActionPerformed(evt);
            }
        });

        panelResultadoSistematica.setBackground(new java.awt.Color(255, 255, 255));
        panelResultadoSistematica.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        textAreaResultadoSistematica.setEditable(false);
        textAreaResultadoSistematica.setColumns(20);
        textAreaResultadoSistematica.setLineWrap(true);
        textAreaResultadoSistematica.setRows(5);
        textAreaResultadoSistematica.setText("\n");
        textAreaResultadoSistematica.setWrapStyleWord(true);
        textAreaResultadoSistematica.setBorder(null);
        jScrollPane7.setViewportView(textAreaResultadoSistematica);

        javax.swing.GroupLayout panelResultadoSistematicaLayout = new javax.swing.GroupLayout(panelResultadoSistematica);
        panelResultadoSistematica.setLayout(panelResultadoSistematicaLayout);
        panelResultadoSistematicaLayout.setHorizontalGroup(
            panelResultadoSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadoSistematicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        panelResultadoSistematicaLayout.setVerticalGroup(
            panelResultadoSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoSistematicaLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSistematicaLayout = new javax.swing.GroupLayout(panelSistematica);
        panelSistematica.setLayout(panelSistematicaLayout);
        panelSistematicaLayout.setHorizontalGroup(
            panelSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSistematicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelResultadoSistematica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSistematicaLayout.createSequentialGroup()
                        .addComponent(panelEntradaSistematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelarSistematica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExecutarSistematica, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelSistematicaLayout.setVerticalGroup(
            panelSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSistematicaLayout.createSequentialGroup()
                .addGroup(panelSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSistematicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelEntradaSistematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSistematicaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnExecutarSistematica, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarSistematica, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultadoSistematica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogAmostragemSistematicaLayout = new javax.swing.GroupLayout(dialogAmostragemSistematica.getContentPane());
        dialogAmostragemSistematica.getContentPane().setLayout(dialogAmostragemSistematicaLayout);
        dialogAmostragemSistematicaLayout.setHorizontalGroup(
            dialogAmostragemSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSistematica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogAmostragemSistematicaLayout.setVerticalGroup(
            dialogAmostragemSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSistematica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogAmostragemSistematica.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 420));
        setMinimumSize(new java.awt.Dimension(600, 420));
        setPreferredSize(new java.awt.Dimension(600, 420));
        setResizable(false);

        jPanelHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(230, 230));
        jLabel1.setMinimumSize(new java.awt.Dimension(230, 230));
        jLabel1.setPreferredSize(new java.awt.Dimension(230, 230));

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        JTabbedPane.addTab("INÍCIO", jPanelHome);

        jPanelAleatoria.setBackground(new java.awt.Color(255, 255, 255));

        textAreaSobreAleatoria.setEditable(false);
        textAreaSobreAleatoria.setColumns(20);
        textAreaSobreAleatoria.setLineWrap(true);
        textAreaSobreAleatoria.setRows(5);
        textAreaSobreAleatoria.setText("Uma amostra aleatória simples é aquela obtida de tal modo que todos os indivíduos da população têm igual probabilidade de serem selecionados.Para se obter uma amostra aleatória simples, atribui-se, inicialmente, um número de ordem a cada elemento da população. A seguir, por meio de um dispositivo aleatório qualquer, seleciona-se ao acaso a quantidade  desejada de indivíduos. Um procedimento aleatório a ser utilizado pode  ser colocar em uma urna todos os números que serão submetidos ao sorteio, retirando depois alguns às cegas. \n\nPode-se ainda usar  os  números  de  loteria  sorteados  nos  últimos  anos,  ou  uma  tabela  de  números  aleatórios,  ou  ainda programas de computador para selecionar aleatoriamente os componentes da amostra.Um ponto importante a salientar é que, usando este procedimento, nenhum indivíduo, por ter esta ou aquela característica, terá oportunidade maior de ser escolhido, pois a escolha independe da vontade do selecionador da amostra.");
        textAreaSobreAleatoria.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textAreaSobreAleatoria);

        btnComReposicao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnComReposicao.setText("COM REPOSIÇÃO");
        btnComReposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComReposicaoActionPerformed(evt);
            }
        });

        btnSemReposicao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSemReposicao.setText("SEM REPOSIÇÃO");
        btnSemReposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemReposicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAleatoriaLayout = new javax.swing.GroupLayout(jPanelAleatoria);
        jPanelAleatoria.setLayout(jPanelAleatoriaLayout);
        jPanelAleatoriaLayout.setHorizontalGroup(
            jPanelAleatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAleatoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAleatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelAleatoriaLayout.createSequentialGroup()
                        .addComponent(btnComReposicao, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSemReposicao, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAleatoriaLayout.setVerticalGroup(
            jPanelAleatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAleatoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAleatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSemReposicao)
                    .addComponent(btnComReposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelAleatoriaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnComReposicao, btnSemReposicao});

        JTabbedPane.addTab("AMOSTRAGEM ALEATÓRIA", jPanelAleatoria);

        jPanelSistematica.setBackground(new java.awt.Color(255, 255, 255));

        textAreaSobreSistematica.setColumns(20);
        textAreaSobreSistematica.setLineWrap(true);
        textAreaSobreSistematica.setRows(5);
        textAreaSobreSistematica.setText("Às vezes, a população é constituída de subpopulações ou estratos e pode ser razoável supor que a variável de interesse apresenta comportamento diferente nos distintos estratos. Neste caso, para que uma amostra  seja  representativa,  ela  deve  apresentar  a  mesma  estratificação  do  universo  de  origem.  Para garantir que o procedimento aleatório produza uma amostra estratificada adequada, deve-se:\n1. Verificar quais os estratos presentes na população.\n2. Calcular seus tamanhos relativos (proporções).\n3. Determinar o tamanho dos estratos na amostra, observando estas mesmas proporções.\n4.  Obter  aleatoriamente  os  elementos  para  cada  estrato,  ou  sorteando  dentro  de  cada  estrato,  ou sorteando dentro da população e preenchendo os espaços reservados para cada estrato.");
        textAreaSobreSistematica.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textAreaSobreSistematica);

        btnSistematica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSistematica.setText("AMOSTRAGEM SISTEMÁTICA");
        btnSistematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistematicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSistematicaLayout = new javax.swing.GroupLayout(jPanelSistematica);
        jPanelSistematica.setLayout(jPanelSistematicaLayout);
        jPanelSistematicaLayout.setHorizontalGroup(
            jPanelSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSistematicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSistematica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSistematicaLayout.setVerticalGroup(
            jPanelSistematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSistematicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistematica, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        JTabbedPane.addTab("AMOSTRAGEM SISTEMÁTICA", jPanelSistematica);

        jPanelSobre.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelSobreLayout = new javax.swing.GroupLayout(jPanelSobre);
        jPanelSobre.setLayout(jPanelSobreLayout);
        jPanelSobreLayout.setHorizontalGroup(
            jPanelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelSobreLayout.setVerticalGroup(
            jPanelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        JTabbedPane.addTab("SOBRE", jPanelSobre);

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPane)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldTamanhoPopulacaoComRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTamanhoPopulacaoComRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTamanhoPopulacaoComRepActionPerformed

    private void btnComReposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComReposicaoActionPerformed
        // TODO add your handling code here:
        dialogAleatoriaComReposicao.setVisible(true);
    }//GEN-LAST:event_btnComReposicaoActionPerformed

    private void btnSemReposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemReposicaoActionPerformed
        // TODO add your handling code here:
        dialogAleatoriaSemReposicao.setVisible(true);
    }//GEN-LAST:event_btnSemReposicaoActionPerformed

    private void btnSistematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistematicaActionPerformed
        // TODO add your handling code here:
        dialogAmostragemSistematica.setVisible(true);
    }//GEN-LAST:event_btnSistematicaActionPerformed

    private void btnExecutarSemRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarSemRepActionPerformed
        // TODO add your handling code here:
        amostragem.aleatoriaSemReposicao(this);
    }//GEN-LAST:event_btnExecutarSemRepActionPerformed

    private void btnCancelarSemRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSemRepActionPerformed
        // TODO add your handling code here:
        dialogAleatoriaSemReposicao.dispose();
    }//GEN-LAST:event_btnCancelarSemRepActionPerformed

    private void btnExecutarComRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarComRepActionPerformed
        // TODO add your handling code here:
        amostragem.aleatoriaComReposicao(this);
    }//GEN-LAST:event_btnExecutarComRepActionPerformed

    private void btnCancelarComRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarComRepActionPerformed
        // TODO add your handling code here:
        dialogAleatoriaComReposicao.dispose();
    }//GEN-LAST:event_btnCancelarComRepActionPerformed

    private void btnCancelarSistematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSistematicaActionPerformed
        // TODO add your handling code here:
        dialogAmostragemSistematica.dispose();
    }//GEN-LAST:event_btnCancelarSistematicaActionPerformed

    private void btnExecutarSistematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarSistematicaActionPerformed
        // TODO add your handling code here:
        amostragem.sistematica(this);
    }//GEN-LAST:event_btnExecutarSistematicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewPrincipal view = new ViewPrincipal();
                view.setLocationRelativeTo(null);
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JButton btnCancelarComRep;
    private javax.swing.JButton btnCancelarSemRep;
    private javax.swing.JButton btnCancelarSistematica;
    private javax.swing.JButton btnComReposicao;
    private javax.swing.JButton btnExecutarComRep;
    private javax.swing.JButton btnExecutarSemRep;
    private javax.swing.JButton btnExecutarSistematica;
    private javax.swing.JButton btnSemReposicao;
    private javax.swing.JButton btnSistematica;
    private javax.swing.JDialog dialogAleatoriaComReposicao;
    private javax.swing.JDialog dialogAleatoriaSemReposicao;
    private javax.swing.JDialog dialogAmostragemSistematica;
    private javax.swing.JTextField fieldTamanhoAmostraComRep;
    private javax.swing.JTextField fieldTamanhoAmostraSemRep;
    private javax.swing.JTextField fieldTamanhoAmostraSistematica;
    private javax.swing.JTextField fieldTamanhoPopulacaoComRep;
    private javax.swing.JTextField fieldTamanhoPopulacaoSemRep;
    private javax.swing.JTextField fieldTamanhoPopulacaoSistematica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelAleatoria;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSistematica;
    private javax.swing.JPanel jPanelSobre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel panelAleatoriaSemReposicao;
    private javax.swing.JPanel panelComRep;
    private javax.swing.JPanel panelEntradaComRep;
    private javax.swing.JPanel panelEntradaSemRep;
    private javax.swing.JPanel panelEntradaSistematica;
    private javax.swing.JPanel panelResultadoComRep;
    private javax.swing.JPanel panelResultadoSemRep;
    private javax.swing.JPanel panelResultadoSistematica;
    private javax.swing.JPanel panelSistematica;
    private javax.swing.JTextArea textAreaResultadoComReposicao;
    private javax.swing.JTextArea textAreaResultadoSemReposicao;
    private javax.swing.JTextArea textAreaResultadoSistematica;
    private javax.swing.JTextArea textAreaSobreAleatoria;
    private javax.swing.JTextArea textAreaSobreSistematica;
    // End of variables declaration//GEN-END:variables
}
